{{- if and .Values.gateway .Values.gateway.enabled .Values.primaryDomain .Values.primaryDomain.enabled }}
{{- if .Values.primaryDomain.tls }}
{{- if ne .Values.primaryDomain.tls.secretNamespace .Values.gateway.namespace }}
# ReferenceGrant allows Gateway to access TLS secret from another namespace
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-tls-{{ .Values.primaryDomain.tls.secretName }}
  namespace: {{ .Values.primaryDomain.tls.secretNamespace }}
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: {{ .Values.gateway.namespace }}
  to:
  - group: ""
    kind: Secret
    name: {{ .Values.primaryDomain.tls.secretName }}
{{- end }}
{{- end }}
{{- end }}
